test:
    path: /test/{id}/{filter}
    defaults:
        _controller: 'GeorgPreissl\Imagefilter\ImagefilterController::loadAction'
        _scope: backend
        _token_check: false
        id: 0
        filter:  0