imagefilter:
    path: /imagefilter/{id}/{filter}
    defaults:
        _controller: 'GeorgPreissl\Imagefilter\Controller\ImagefilterController::loadAction'
        _scope: backend
        _token_check: false
        id: 0
        filter:  0